const usFirstNames = ["Ahmed", "Ryne", "Jaliah", "Angie", "Zofia", "Davis", "Teigen", "Truitt", "Nehemiah", "Giulianna", "Dottie", "Alizae", "Marietta", "Orion", "Melina", "Neely", "Tariq", "Lenna", "Katya", "Saray", "Rocket", "Aayla", "Amari", "Goldie", "Joelle", "Ayra", "Marlon", "Moriah", "Mihir", "Raena", "Emri", "Bennie", "Rae", "Ximena", "Giulietta", "Chaya", "Aviel", "Rueben", "Michal", "Trey", "Naima", "Jaylen", "Jayven", "Aleksey", "Noam", "Esme", "Torrey", "Rilyn", "Ezrah", "Jami", "Ellery", "Jeffry", "Sriram", "Zoha", "Blima", "Glen", "Niklaus", "Tennessee", "Candy", "Canton", "Madina", "Sigrid", "Jaide", "Lilla", "Larissa", "Oaklie", "Jed", "Jaylyn", "Arjun", "Alexi", "Alanie", "Stephon", "Lundyn", "Vita", "Gisela", "Sidney", "Andrei", "Jazelle", "Bryndle", "Donnell", "Kale", "Walker", "Sabastian", "Yuvan", "Azucena", "Koral", "Alexis", "Unity", "Hafsa", "Rossy", "Charli", "Aziyah", "Gwendolynn", "Amaiya", "Scarlett", "Sevyn", "Lark", "Cassie", "Kendalynn", "Drew", "Kehlani", "Yohan", "Kirah", "Rayla", "Seven", "Jordin", "Glory", "Vail", "Giabella", "Fabiola", "Hosanna", "Hafsah", "Vivianne", "Kalani", "Alaa", "Rumi", "Reese", "Jade", "Aylen", "Alani", "Ilyana", "Isacc", "Jacoby", "Gerson", "Alia", "Rielle", "Natali", "Mister", "Carissa", "Colton", "Camrynn", "Tehila", "Mykayla", "Brisa", "Oaklee", "Keylin", "Raelynn", "Breanne", "Myla", "Amylia", "Leidy", "Case", "Fischer", "Lyla", "Kitana", "Kacen", "Amelia", "Verity", "Josie", "Calum", "Yamen", "Tj", "Kavin", "Audie", "Cai", "Cydney", "Kenadi", "Khari", "Emiyah", "Kallan", "Iyana", "Moshe", "Safaa", "Reid", "Klynn", "Abdulrahman", "Ronny", "Viviana", "Delta", "Brynley", "Chiara", "Candice", "Mikah", "Rowyn", "Dutch", "Idris", "Batya", "Carleigh", "Lexa", "Musab", "Keri", "Zaara", "Aycen", "Marshawn", "Disha", "Sailor", "Mccoy", "Aleeyah", "Cameron", "Maiyah", "Emrys", "Drew", "Bauer", "Glenda", "Miracle", "Jalen", "Keisi", "Flora", "Anaiah", "Niah", "Jai", "Kollins", "Divya", "Cort", "Lucie", "Kami", "Brecken", "Summit", "Jude", "Mirabelle", "Joseline", "Taleah", "Rocco", "Bentlee", "Lacy", "Zianna", "Sharon", "Khalia", "Ainhoa", "Meena", "Georgianna", "Azelia", "Douglas", "Scarlet"];

const usLastNames = ["Dickerson", "Osborn", "Dennis", "Bush", "Cantu", "Taylor", "Medina", "Crawford", "Schroeder", "Perkins", "Waller", "Randolph", "Reese", "Wall", "Manning", "Paul", "Watkins", "Glover", "Hansen", "Blackwell", "Coleman", "Ellis", "Perry", "Griffin", "Buck", "Moody", "Blankenship", "Church", "Mcintosh", "Simpson", "Summers", "Gould", "Burke", "Montgomery", "George", "Blair", "Jarvis", "Dominguez", "Scott", "Blanchard", "Lawson", "Watts", "Mcconnell", "Page", "Campbell", "Jackson", "Flynn", "Dickson", "Chandler", "Arias", "Yoder", "Woodard", "Maxwell", "Serrano", "Mooney", "Dunn", "Conner", "Franklin", "Davis", "Pham", "Hampton", "Mullen", "Levine", "Pennington", "Cantrell", "Massey", "Bartlett", "Mccarthy", "Sloan", "Stark", "Cherry", "Hoffman", "Petersen", "Ferguson", "Terrell", "Townsend", "Estes", "Shaw", "Rivera", "Sawyer", "Orr", "Sharp", "Ayala", "Dixon", "Calderon", "Powell", "Harrison", "Rowe", "Barber", "Goodman", "Trevino", "Ritter", "Mcknight", "Gross", "Giles", "Stein", "Patton", "Johns", "Evans", "Walsh", "Delacruz", "Parker", "Herman", "Reed", "Holder", "Rangel", "Rich", "Byrd", "Bright", "Vazquez", "Middleton", "Ali", "Sanchez", "Gardner", "Hickman", "Copeland", "Hines", "Harper", "Burton", "Avila", "Fox", "Compton", "Haynes", "Madden", "Bauer", "Parrish", "Hooper", "Ibarra", "Cobb", "Thornton", "Santiago", "Quinn", "Hall", "Stephens", "Long", "Silva", "Michael", "Dean", "Fitzgerald", "Berry", "Leon", "Eaton", "Mcfarland", "Whitehead", "Garza", "Alvarez", "Carr", "Le", "Reeves", "Oconnell", "Zamora", "Hanna", "Houston", "Jones", "Wilcox", "Erickson", "Stanley", "Tucker", "Curtis", "Berger", "Santana", "Gonzales", "Malone", "Wyatt", "Moreno", "Kelley", "Christian", "Haney", "Benjamin", "Barajas", "Stephenson", "Riley", "Booker", "Haley", "Vincent", "Navarro", "Brandt", "Roberson", "Reilly", "Lambert", "Macdonald", "Brennan", "Roth", "Golden", "Burgess", "Davila", "Owens", "Christensen", "Sweeney", "Bird", "Glenn", "Bautista", "Rivers", "Woodward", "Hinton", "Callahan", "Barnes", "Oliver"];

const usMiddlenames = ["Lawrence", "Brock", "Avery", "Louisa", "Taylore", "Amity", "Aiden", "Beck", "Timothy", "Benjamin", "June", "Carleen", "Cody", "Sean", "Annabel", "Aryn", "Everett", "Bram", "Trey", "Marcella", "Amelia", "Kingston", "Daniel", "Dean", "Blanche", "Varian", "Silvia", "Anthony", "Ace", "Julian", "Oscar", "Haiden", "Vernon", "Gavin", "Devon", "Dash", "Preston", "Annora", "Irene", "Brighton", "Dominick", "Drake", "Coreen", "Sharon", "Adele", "Raven", "Apollo", "Byron", "Caprice", "Miriam", "Lillian", "Imogen", "Coy", "Wade", "Felix", "Rhett", "Eloise", "Juan", "Rose", "Garrison", "Abigail", "Anise", "Kai", "Kylie", "Harriet", "Ellen", "Ashten", "Carlen", "Cameron", "Bailey", "Will", "Coralie", "Julian", "Conrad", "Reagan", "Marguerite", "Gabriel", "Oren", "Blayne", "Linnea", "Isaac", "Zachary", "Krystan", "Tanner", "Tristan", "Lilibeth", "Ellory", "Caleb", "Korin", "Cerise", "Arthur", "Joseph", "Natalie", "Aryn", "Blake", "Adelaide", "Elias", "Dex", "Trevor", "Caren", "Fernando", "James", "Damon", "Xavier", "Quintin", "Madisen", "Tyson", "Rene", "Olive", "Ann", "Elijah", "Sullivan", "Bree", "Jack", "Vanessa", "Jacklyn", "Noah", "George", "Lee", "Jeremy", "Jackson", "Blair", "Emeline", "Dezi", "Lucinda", "Lynn", "Reeve", "Monteen", "Kent", "Alice", "Leo", "Evelyn", "Blake", "Nevin", "Bianca", "Ricardo", "Ellison", "Thomas", "Troy", "Jaidyn", "Matilda", "Dante", "Doran", "Javan", "Syllable", "Finn", "Denise", "Justice", "Vivian", "Cash", "Fern", "Viola", "Rory", "Karilyn", "Clark", "Naveen", "Hope", "Claude", "Payten", "Murphy", "Lane", "Myron", "Joanna", "Sutton", "Jasper", "Emerson", "Vincent", "Zion", "Naomi", "Tobias", "William", "Brooke", "Aaron", "Kae", "Kalan", "Erin", "Leonie", "Brandt", "Candice", "Coralie", "Eli", "Juliet", "Charles", "Sue", "Marcellus", "Verena", "Zoe", "Harrison", "Gillian", "Dustin", "Sophia", "Suzan", "Bernice", "Brett", "Justin", "Matteo"];

const usCities = ["Aberdeen", "Aberdeen", "Aberdeen", "Aberdeen", "Avalon", "Avalon", "Avani", "Adventure", "Avila Beach", "Avistan", "Avoca", "Aurora", "Aurora", "Aurora", "Aurora", "Agora Hills", "Adams", "Adams", "Adamstown", "Adelanto", "Adele", "Hadrian", "Azusa", "Aiken", "Ivins", "Aida Grove", "Idaho Springs", "Idaho Falls", "In Idyllway", "Aidlade Park", "Ayen Mountain", "Ayen River", "Aienwood", "Aizellin", "Isle of Pams", "Island Park", "Island Park", "Iowa", "Iowa City", "Iowa Falls", "Ayola", "Aoni", "Irondale", "Ironton", "Not to mention", "White", "Aqua Harbor", "Acme", "Acre", "Alabaster", "Alameda", "Alamo", "in Alamogordo", "Alamosa", "Alachua", "Albert Lee", "Albertville", "Albertville", "Algoma", "Algona", "Algonquin", "Alexander City", "Alexandria", "Alexandria", "Alexandria", "Alexandria Bay", "Aliso-Vyeho", "Allegan", "Allegany", "Allen", "Allen Park", "Allendale", "allentown", "Aloha", "Alton Bay", "Alhambra", "Alba", "Albion", "Albuquerque", "Alva", "Alvarado", "Alvin", "Alcoa", "Alma", "Alma", "Alma", "Alma", "Alpine", "Alpine", "Alpine", "Alpena", "Alto", "Alto", "Altavista", "Altamont", "Altamonte Springs", "Alton", "Altoona", "Alturas", "Altus", "Alpharetta", "Alliance", "Amador City", "Amarillo", "Amelia", "Amelia City", "Amenia", "American Canyon", "American Fork", "americus", "Amit", "Amsterdam", "Anadarko", "Anaconda", "Anacortes", "Anamosa", "Anaheim", "Anahola", "Angola", "Andalusia", "Anderson", "Anderson", "Anderson", "Anderson", "Andover", "Andreas", "Uncasville", "Anchorage", "Anna", "Anna Maria", "Annawen", "Annandale", "Annapolis", "Annapolis Junction", "Anniston", "Anoka", "Anstead", "Antigo", "Antimony", "Antiochus", "Antiochus", "Antlers", "Antonio", "Antrim", "Apalachicola", "Apalachin", "Apache Junction", "Apex", "Upland", "Apopka", "Upper Lake", "Upper Marlborough", "Upper Sandusky", "Upper Grand Lagoon", "Appomattox", "Arabic", "Aransas Pass", "Arvada", "Arden Hills", "Arden, Asheville", "Ardmore", "Ardmore", "Arkadelphia", "Arcadia", "Arcadia", "Arcadia", "Arkansas City", "The arch", "Arkdale", "Arcola", "Arlington", "Arlington", "Arlington", "Arlington", "Arlington", "Armonk", "Arnold", "Arnold", "Arnolds Park", "Arroyo Grande", "Arroyo Seco", "Artesia", "Artesia", "Archdale", "Askatni", "Aspermon", "Astoria", "hacienda heights", "Atascadero", "Athens"];

const usStreets = ["Damen", "State", "Lsd grand av", "35th", "Kostner", "Devon", "Vincennes", "Woodlawn", "Lsd columbus dr", "Lawrence", "Irving park", "Stevenson", "Irving park", "Garfield", "Kedzie", "Cicero", "Kennedy", "Eisenhower", "Harrison", "51st", "Dan ryan express", "Devon", "Chicago skyway", "Belmont", "California", "99th", "Pershing", "Peterson", "26th", "99th", "103rd", "Devon", "Belmont", "Bishop ford", "Western", "Ogden", "Kedzie", "119th", "California", "Kennedy", "Devon", "Archer", "Central", "Dan ryan 43rd st", "35th", "Kostner", "Kennedy pulaski rd", "Milwaukee", "Fullerton", "Cicero", "59th", "16th", "Caldwell", "Damen", "Central park", "Ewing", "Madison", "Halsted", "Diversey", "Van buren", "Michigan", "87th", "51st", "Cottage grove", "Caldwell", "Eisenhower western av", "Dan ryan", "Western", "Dan ryan express", "North", "Central park", "87th", "Kedzie", "47th", "Oak park", "State", "Kostner", "Cumberland", "Cullerton", "111th", "I55 pulaski rd", "Western", "Diversey", "Austin", "51st", "Laramie", "79th", "Racine", "103rd", "Laramie", "75th", "75th", "Armitage", "111th", "Lincoln", "Dan ryan express", "59th", "Chicago", "111th", "Racine"];

const usAlphabet = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0"];

const byFirstNames = ["Абрамовіч", "Абрамчык", "Абрамчук", "Аўраменка", "Аўрамчык", "Аўтыменя", "Аўхіменя", "Агейчык", "Адаменя", "Адамовіч", "Адамчук", "Азаранка", "Акінчыц", "Аксючыц", "Акуліч", "Алейнікаў", "Аляксандраў", "Аляксандравіч", "Аляксееў", "Аляксеенка", "Аляксейчык", "Аляшкевіч", "Алешка", "Альховік", "Альшэўскі", "Амяльчэня", "Ананіч", "Андрэеў", "Андрэйчык", "Андраюк", "Андрончык", "Анішчанка", "Анціпенка", "Антоненка", "Антонаў", "Антановіч", "Антончык", "Антанюк", "Арыніч", "Арцёменка", "Арцёмчык", "Арціменя", "Арцыменя", "Астапенка", "Астапаў", "Астапчык", "Асташонак", "Асташонак", "Астрэйка", "Атрошчанка", "Афанасенка", "Ахраменя", "Ахрэмчык", "Бабеня", "Бабініч", "Бабіцкі", "Бабіч", "Бабак", "Базылец", "Баранаў", "Бараноўскі", "Баранчык", "Баранчук", "Баркоўскі", "Барсук", "Барташэвіч", "Белы", "Бялько", "Бельскі", "Бяляўскі", "Бяляеў", "Беразоўскі", "Бібік", "Бірук", "Блізнюк", "Бабко", "Бобка", "Бобка", "Бобр", "Бобрык", "Бабёр", "Багданаў", "Багдановіч", "Багдзевіч", "Бажко", "Бажок", "Бойка", "Бондараў", "Бандарэнка", "Бандарык", "Бандарчык", "Бандарчук", "Бондар", "Барэйка", "Барысевіч", "Барысенка", "Барысёнак", "Барысік", "Барысаў", "Барысавец", "Барысюк", "Барычэўскі", "Баравік", "Бароўскі", "Барадзеня", "Бародзіч", "Борсук", "Баярчук", "Брагінец", "Будзько", "Буйко", "Булаўка", "Булойчык", "Булыга", "Бурак", "Бурко", "Бусько", "Буцько", "Бык", "Быкоўскі", "Быхавец", "Бычок", "Бычкоўскі", "Бяценя", "Вакульчык", "Вакульчык", "Валюк", "Валюк", "Варвашэня", "Васілевічы", "Васілеўскі", "Васіленка", "Васілёнак", "Васільеў", "Васілюк", "Васько", "Васюк", "Вашкевіч", "Вялічка", "Вярбіцкі", "Вяргейчык", "Верамейчык", "Вярэніч", "Вінаград", "Віткоўскі", "Вішнеўскі", "Уладыка", "Уласенка", "Уласюк", "Улашчык", "Водчыц", "Войцік", "Вайтовіч", "Войцехаў", "Ваўка", "Валадзько", "Валасюк", "Волчак", "Ваўчок", "Верабей", "Верабей", "Крумкач", "Варанько", "Урублеўскі", "Высоцкі", "Гаўрыленка", "Гаўрыленя", "Гаўрылаў", "Гаўрыльчык", "Гаўрылюк", "Гайдук", "Гайшун", "Галушка", "Гапоненка", "Гегеня", "Герасіменка", "Герасімёнак", "Герасіменя", "Герасімаў", "Герасімовіч", "Герасімчык", "Герасімчук", "Глінскі", "Галёнак", "Голік", "Галаўко", "Галоўчыц", "Голуб", "Голубеў", "Голубеў", "Ганчар", "Ганчарэнка", "Ганчаронак", "Ганчарык", "Ганчар"];

const byLastNames = ["Сібіла", "Дыядора", "Адэля", "Вір", "Вілорыя", "Адам", "Валянціна", "Паўсіліп", "Вераслава", "Платон", "Антыгон", "Праўдзіна", "Боян", "Ермінінгельд", "Святлана", "Кара", "Фартуната", "Ахія", "Дзеля міру", "Фёдар", "Мамій", "Марыя", "Агапа", "Уладзіслава", "Светомир", "Вілібальд", "Афра", "Оскар", "Эміліяна", "Авудзім", "Яўціхія", "Анін", "Улас", "Карп", "Альбіна", "Януарый", "Свеціслава", "Пір", "Эпіктэт", "Уладзілен", "Мацільда", "Мацей", "Акіян", "Геронт", "Эдзіта", "Акадэміі", "Аляксей", "Евагрый", "Яўграф", "Сцяпан", "Прот", "Клімент", "Венера", "Клаўдзіян", "Ілій", "Прапіў", "Коінт", "Агапій", "Владан", "Віфоній", "Дарый", "Мацвей", "Ізяслаў", "Кандіда", "Вар", "Войцех", "Іраіда", "Валенсія", "Засім", "Зара", "Звяніміра", "Мацей", "Ждана", "Дзянісся", "Сільвія", "Эпафрас", "Аўрэліян", "Засім", "Алегра", "Чэслава", "Дзей", "Юстын", "Арсенія", "Прапіў", "Ціт", "Аляна", "Кірыякія", "Донара", "Муза", "Жаклін", "Урван", "Мілаваць", "Боян", "Ліпацій", "Ахіл", "Уладзіслаў", "Мікіта", "Арцём", "Данііл", "Алеся", "Яна", "Ганна", "Кірыла", "Куарт", "Віталіян", "Іанікіт", "Нектарый", "Авіяфа", "Гран", "Амельфа", "Рагнеда", "Актион", "Юльяна", "Элін", "Ерм", "Гурэй", "Уладлен", "Юстына", "Зарававэль", "Ор", "Глікерыя", "Клеапатра", "Юліта", "Лонгіна", "Гарыслава", "Ефрасій", "Эміліяна", "Рувін", "Агафодор", "Еўмінія", "Неаніла", "Пістымея", "Марым'яна", "Меней", "Апалос", "Арыён", "Лука", "Дыяніна", "Кацярына", "Філіп", "Лукій", "Велеслава", "Пассик", "Ахілій", "Мялецій", "Мардар", "Адысея", "Генадзь", "Стэфан", "Юстына", "Захар", "Діор", "Калінікія", "Вестыта", "Міхайла", "Велімір", "Нікандр", "Асан", "Алімпіян", "Апелій", "Магна", "Патрокл", "Марыя", "Гартэнзія", "Патэрмуфій", "Надзея", "Ганна", "Яраміл", "Клаўдзіян", "Лучазара", "Гаргонія", "Дарыя"];

const byMiddlNames = ["Аляксандравіч", "Аляксеевіч", "Анатольевіч", "Андрэевіч", "Антановіч", "Аркадзьевіч", "Арсеньевіч", "Арцёмавіч", "Апанасавіч", "Багдановіч", "Барысавіч", "Вадзімавіч", "Валянцінавіч", "Валерыевіч", "Васільявіч", "Віктаравіч", "Вітальевіч", "Уладзіміравіч", "Усеваладавіч", "Вячаслававі", "Гаўрыловіч", "Генадзевіч", "Георгіевіч", "Глябовіч", "Рыгоравіч", "Давыдовіч", "Даніловіч", "Дзянісавіч", "Дзмітрыевіч", "Яўгенавіч", "Ягоравіч", "Емяльянавіч", "Яфімавіч", "Іванавіч", "Ігаравіч", "Ільіч", "Іосіфавіч", "Кірылавіч", "Канстанцінавіч", "Карнеевіч", "Леанідавіч", "Львовіч", "Макаравіч", "Максімовіч", "Маркавіч", "Мацвеевіч", "Мітрафанавіч", "Міхайлавіч", "Назаровіч", "Навумовіч", "Мікалаевіч", "Алегавіч", "Паўлавіч", "Пятровіч", "Платонавіч", "Робертавіч", "Радзівонавіч", "Рамановіч", "Савельевіч", "Сямёнавіч", "Сяргеевіч", "Станіслававіч", "Сцяпанавіч", "Тарасавіч", "Цімафеевіч", "Ціхановіч", "Фёдаравіч", "Феліксавіч", "Філіповіч", "Эдуардавіч", "Якаўлевіч", "Яраслававіч"];

const byCities = ["Баранавічы", "Іванава", "Петрыкаў", "Барань", "Івацэвічы", "Пінск", "Белаазёрск", "Іўе", "Полацк", "Бялынічы", "Бяроза", "Калінкавічы", "Пружаны", "Беразіно", "Камянец", "Бярозаўка", "Кіраўск", "Рэчыца", "Бабруйск", "Клецк", "Рагачоў", "Барысаў", "Клімавічы", "Браслаў", "Клічаў", "Светлагорск", "Брэст", "Кобрын", "Свіслач", "Буда-Кашалёва", "Капыль", "Сянно", "Быхаў", "Косав", "Касцюковічы", "Слаўгарад", "Васілевічы", "Крычаў", "Слонім", "Верхнядзвінск", "Круглае", "Слуцк", "Ветка", "Крупкі", "Смалявічы", "Вілейка", "Смаргонь", "Віцебск", "Лепель", "Салігорск", "Ваўкавыск", "Ліда", "Старыя Дарогі", "Валожын", "Лагойск", "Стоўбцы", "Высокае", "Лунінец", "Столін", "Любань", , "Ганцавічы", "Ляхавічы", "Талачын", "Глыбокае", "Тураў", "Гомель", "Маларыта", "Горкі", "Мар'іна Горка", "Узда", "Гарадок", "Мікашэвічы", "Гродна", "Мінск", "Фаніпаль", "Міёры", "Давыд-Гарадок", "Магілёў", "Хойнікі", "Дзяржынск", "Мазыр", "Дзісна", "Маладзечна", "Чавусы", "Добруш", "Масты", "Чашнікі", "Докшыцы", "Мсціслаў", "Чэрвень", "Драгічын", "Мядзель", "Чэрыкаў", "Дуброўна", "Чачэрск", "Дзятлава", "Нароўля", "Нясвіж", "Шклоў", "Ельск", "Навагрудак", "Новалукомль", "Шчучын", "Жабінка", "Наваполацк", "Жыткавічы", "Жлобін", "Орша", "Жодзіна", "Асіповічы", "Астравец", "Заслаўе", "Ашмяны"];

const byStreets = ["Абрыкосавая вул.", "Авакяна вул.", "Авангардная вул.", "Авангардны зав.", "Аўрароўская вул.", "Аўтадароўская вул.", "Аўтадораўскі зав.", "Аўтазаводская вул.", "Аўтазаводскі зав.", "Аўтамабілістаў вул.", "Агатавы зав.", "Азгура вул.", "Азізава вул.", "Азоўская вул.", "Айвазоўскага зав.", "Айвазоўскага вул.", "Акадэміка Высоцкага вул.", "акадэміка Вышалескага зав.", "акадэміка Вышалескага вул.", "Акадэміка Жэбрака зав.", "Акадэміка Жэбрака вул.", "Акадэміка Карскага вул.", "Акадэміка Красіна вул.", "акадэміка Купрэвіча вул.", "акадэміка Фёдарава вул.", "Акадэмічная вул.", "Аладавых вул.", "Аляксандраўская вул.", "Алеся бачыла вул.", "Алеся Гаруна вул.", "Алеся Дудара вул.", "Алібегава вул.", "Алейная вул.", "Алтайская вул.", "Алтайскі зав.", "Амбулаторная вул.", "Амбулаторны зав.", "Амуратарская вул.", "Амурская вул.", "Амурскі зав.", "Ангарская вул.", "Ангарскі зав.", "Андрэеўская вул.", "Анаева вул.", "Антоненка вул.", "Антонаўская вул.", "Апалінар'еўская вул.", "Аранская вул.", "Аркадзя Смоліча вул.", "Арктычная 1-я вул.", "Арцёма 1-ы зав.", "Арцёма 1-ы праезд", "Арцёма вул.", "Артылерыстаў вул.", "Асаналіева зав.", "Асаналіева вул.", "Ауэзава вул.", "Аэрадромная вул.", "Аэрадромны зав.", "Аэрафлоцкая вул.", "Аэрафлоцкі 1-ы зав.", "Бабушкіна вул.", "Баграціёна 1-ы зав.", "Баграціёна 2-гі зав.", "Баграціёна вул.", "Барвовая вул.", "Багранцава вул.", "Барвовы зав.", "Базісная 1-я вул.", "Базісная 2-я вул.", "Базісны зав.", "Байкальская вул.", "Бакінская вул.", "Балтыйская вул.", "Бангалор ПЛОШЧА", "Барамзінай вул.", "Бараноўшчына вул.", "Басіялоўскі 1-ы зав.", "Басіялоўскі 2-гі зав.", "Баторынская вул.", "Баторынскі зав.", "Бачыла Алеся вул.", "Бягомльская вул.", "Бяды вул.", "Бялецкага вул.", "Бялінскага вул.", "Беламорская вул.", "Беларуская вул.", "БЕЛАРУСКІ 2-гі зав.", "Бельскага вул.", "Бельчыцкая вул.", "Бяляева вул.", "Бярэзінская вул.", "Берасцянская вул.", "Берсана вул.", "Берута вул.", "Бетонны праезд", "Бехцерава зав.", "Бехцерава вул.", "Бібліятэчная вул.", "Бірузова вул.", "Бабруйская вул.", "Багдановіча Максіма зав.", "Багдановіча Максіма вул.", "Багушэвіча ПЛОШЧА", "Балотная вул.", "Балотнікава зав.", "Балотнікава вул.", "Балотны зав.", "Бальнічны зав.", "Вялікая Сляпнёў вул.", "бор Сасновы вул.", "Баравецкі зав.", "Барадзінская вул.", "Батанічная вул.", "Брагінская вул.", "Брагінскі 1-ы зав.", "Брагінскі 2-гі зав.", "Брацкая вул.", "Брацкі зав.", "Брэст-Літоўская вул.", "Брэсцкая вул."];

const byAlphabet = ["А", "Б", "В", "Г", "Д", "Дж", "Дз", "Е", "Ё", "Ж", "З", "І", "Й", "К", "Л", "М", "Н", "О", "П", "Р", "С", "Т", "У", "Ў", , "Ф", "Х", "Ц", "Ч", "Ш", "Ы", "Ь", "Э", "Ю", "Я"];


const plFirstNames = ["Lara", "Klementyna", "Justyna", "Adela", "Honorata", "Blanka", "Felicja", "Daniela", "Justyna", "Otylia", "Faustyna", "Bogumila", "Kornelia", "Natalia", "Jolanta", "Bogumila", "Jadwiga", "Jolanta", "Aleksandra", "Klementyna", "Gabriela", "Anna", "Zofia", "Maria", "Wanda", "Izyda", "Paula", "Liliana", "Monika", "Czeslawa", "Milena", "Marlena", "Justyna", "Monika", "Miroslawa", "Aleksandra", "Asia", "Oksana", "Iga", "Olga", "Anatolia", "Roksana", "Judyta", "Franciszka", "Maria", "Martyna", "Agata", "Joanna", "Luiza", "Nikola", "Irena", "Marcelina", "Magda", "Wiktoria", "Ada", "Amanda", "Jozefa", "Jola", "Wiktoria", "Luiza", "Kamila", "Bogda", "Ilona", "Anita", "Kornelia", "Olimpia", "Faustyna", "Julianna", "Wioletta", "Amalia", "Andrea", "Alice", "Malgorzata", "Antonina", "Beata", "Iza", "Julita", "Bernadetta", "Lila", "Lidia", "Paula", "Julita", "Anita", "Olimpia", "Beata", "Iga", "Liliana", "Nina", "Izyda", "Wiktoria", "Marlena", "Roksana", "Marlena", "Anna", "Elena", "Anatolia", "Zuzanna", "Arleta", "Antonina", "Wioletta", "Faustyna", "Wanda", "Elzbieta", "Natalia", "Aneta", "Alicja", "Beata", "Agnieszka", "Danuta", "Blanka", "Celina", "Maja", "Jolanta", "Cecylia", "Malgorzata", "Judyta", "Julita", "Franciszka", "Nikola", "Boguslawa", "Andrea", "Berenika", "Berenika", "Elwira", "Agnieszka", "Dagmara", "Joanna", "Marzanna", "Daniela", "Boguslawa", "Malgorzata", "Czeslawa", "Katarzyna", "Karolina", "Beata", "Helena", "Sylwia", "Kamila", "Lila", "Nikola", "Alicja", "Urszula", "Diana", "Ida", "Florencja", "Adriana", "Aneta", "Arleta", "Felicja", "Regina", "Krystyna", "Marcelina", "Aleksandra", "Edyta", "Wioletta", "Adela", "Klara", "Malwina", "Dominika", "Natasza", "Idalia", "Amalia", "Stanislawa", "Daniela", "Aleksandra", "Jozefa"];

const plLastNames = ["Rutkowski", "Szulc", "Sadowska", "Jaworski", "Wroblewski", "Czerwinski", "Kaczmarczyk", "Szymczak", "Jakubowski", "Mazurek", "Sadowska", "Jasinski", "Piotrowski", "Piotrowski", "Rutkowski", "Gorski", "Kolodziej", "Wlodarczyk", "Kalinowski", "Ziolkowska", "Sadowska", "Sokolowski", "Przybylski", "Chmielewski", "Tomaszewski", "Kozlowski", "Gajewska", "Mroz", "Kalinowski", "Krawczyk", "Rutkowski", "Adamska", "Laskowska", "Zielinski", "Kazmierczak", "Makowski", "Kaczmarczyk", "Maciejewski", "Zielinski", "Jankowski", "Czarnecki", "Krawczyk", "Nowak", "Zielinski", "Brzezinski", "Czerwinski", "Piotrowski", "Czerwinski", "Sikorska", "Bak", "Mazurek", "Laskowska", "Szymanski", "Borkowski", "Szulc", "Makowski", "Zawadzki", "Wisniewski", "Laskowska", "Adamska", "Baranowski", "Kowalski", "Szulc", "Blaszczyk", "Jasinski", "Zawadzki", "Maciejewski", "Wlodarczyk", "Makowski", "Zakrzewska", "Jaworski", "Mazur", "Kucharski", "Urbanska", "Wysocki", "Sikorska", "Jasinski", "Zawadzki", "Kucharski", "Kolodziej", "Zakrzewska", "Sadowska", "Michalak", "Bak", "Kwiatkowski", "Chmielewski", "Pietrzak", "Wisniewski", "Ostrowski", "Jankowski", "Pietrzak", "Lewandowski", "Bak", "Kowalski", "Czarnecki", "Kubiak", "Duda", "Walczak", "Kowalczyk", "Pawlak", "Gorecki", "Gorecki", "Kwiatkowski", "Witkowski", "Marciniak", "Kalinowski", "Jaworski", "Mazurek", "Glowacka", "Wlodarczyk", "Zakrzewska", "Jaworski", "Brzezinski", "Glowacka", "Makowski", "Kwiatkowski", "Pietrzak", "Czarnecki", "Szczepanski", "Szymczak", "Sikorska", "Kozlowski", "Laskowska", "Kaczmarczyk", "Mroz", "Kucharski", "Sikorska", "Sadowska", "Kucharski", "Pietrzak", "Marciniak", "Bak", "Sikora", "Baran", "Wojcik", "Duda", "Szymanski", "Jakubowski", "Lewandowski", "Laskowska", "Krupa", "Baran", "Wroblewski", "Wlodarczyk", "Zielinski", "Maciejewski", "Krawczyk", "Baranowski", "Piotrowski", "Czerwinski", "Kaczmarczyk", "Baran", "Sikora", "Baranowski", "Czerwinski", "Mazur", "Jakubowski", "Zawadzki", "Kowalski", "Kubiak", "Gajewska", "Ostrowski", "Chmielewski", "Piotrowski", "Gorecki", "Baranowski", "Sokolowski", "Makowski", "Jaworski", "Piotrowski", "Kaminski", "Wroblewski", "Jankowski", "Jakubowski", "Dabrowski", "Kalinowski", "Gorski", "Lis", "Chmielewski", "Witkowski", "Blaszczyk", "Wysocki", "Wysocki"];

const plCities = ["Augustow", "Bialystok", "Bielsko-Biala", "Bochnia", "Boleslawiec", "Bukowina Tatrzanska", "Busko-Zdroj", "Bydgoszcz", "Cieszyn", "Czestochowa", "Dabki", "Darlowo", "Dobron", "Duszniki-Zdroj", "Elblag", "Frombork", "Gdansk", "Gdow", "Gdynia", "Gizycko", "Gliwice", "Gniezno", "Gorzow Wielkopolski", "Jastrzebia Gora", "Jawor", "Jaworzno", "Jelenia Gora", "Jerzmanowice", "Jozefow", "Kalisz", "Kalwaria Zebrzydowska", "Karpacz", "Katowice", "Kedzierzyn-Kozle", "Kielce", "Klodzko", "Kobiur", "Kolobrzeg", "Komorniki", "Koscielisko", "Koszalin", "Krakow", "Krynica", "Kudowa Zdroj", "Lagow", "Leba", "Legnica", "Lodz", "Lubania", "Lublin", "Lukta", "Lysomice", "Miedzyzdroje", "Mielno", "Milowka", "Elegantka", "Mragowo", "Muszyna", "Myslakowice", "Naleczow", "Novograd", "Nowy Sacz", "Olesnica", "Olsztyn", "Opole", "Oswiecim", "Parkowanie", "Piekary Slaskie", "Pila", "Plock", "Pobierowo", "Podgorzyn", "Polanica Zdroj", "Pomlewo", "Poznan", "Przemysl", "Raciborz", "Radom", "Rewal", "Rume", "Ryn", "Rzeszow", "Serock", "Slupsk", "Sopot", "Sosnowiec", "Stare Jablonki", "Stenszew", "Suleczyno", "Swinoujscie", "Szczecin", "Szczyrk", "Szklarska Poreba", "Targanice", "Torun", "Tychy", "Ustka", "Ustron", "Walbrzych", "Warszawa", "Wieliczka", "Wisla", "Wladyslawowo", "Wroclaw", "Wronki", "Zabrze", "Zakopane", "Zielona Gora", "Balice", "Bartoszyce", "Belchatow", "Bielawa", "Bedzin", "Benczkow", "Brzeg", "Bolszewo", "Bytom", "Byczyna", "Biala Podlaska", "Bialka", "Bialobrzegi", "Wadowice", "Glebogryzarka Wielka", "Wielun", "Wegrow", "Wieszchowiska", "Wrzesnia", "Wilga", "Wloclawek", "Glogow"];

const plStreets = [ "Ulica 3 Maja", "Ulica 11 Listopada", "Ulica Akademicka", "Ulica gen. Wladyslawa Andersa", "Ulica Armii Krajowej", "Ulica Balonowa", "Ulica Michala Baluckiego", "Ulica Bankowa", "Ulica Jozefa Bema", "Ulica Bernardynska", "Ulica Beskidzka", "Ulica Bialoskornicza", "Ulica Bielska", "Ulica Bohaterow Monte Cassino", "Ulica Bozego Ciala", "Ulica Bracka", "Ulica Browarna", "Ulica Brzeska", "Ulica Bytomska", "Ulica Chlodna", "Ulica Chmielna", "Ulica Fryderyka Chopina", "Ulica Chorzowska", "Ulica Boleslawa Chrobrego", "Ulica Ciasna", "Ulica Ciepla", "Ulica Stefana Czarnieckiego", "Ulica Czestochowska", "Ulica Jana Henryka Dabrowskiego", "Ulica Dluga", "Ulica Dworcowa", "Ulica Dyrekcyjna", "Elblaska", "Ulica Fabryczna", "Ulica Farna", "Ulica Florianska", "Ulica Franciszkanska", "Ulica Francuska", "Ulica Aleksandra Fredry", "Ulica Gajowa", "Ulica Garbarska", "Ulica Garncarska", "Ulica Gdanska", "Ulica Gliniana", "Ulica Gliwicka", "Ulica Bartosza Glowackiego", "Ulica Gnieznienska", "Golebia", "Ulica Gornoslaska", "Ulica Graniczna", "Ulica Grodzka", "Ulica Artura Grottgera", "Ulica Grunwaldzka", "Ulica Gwarna", "Ulica Hallera", "Ulica Hetmanska", "Ulica Hrubieszowska", "Ulica Swietego Idziego", "Inzynierska", "Ulica Jagiellonska", "Ulica Jana Pawla II", "Ulica Jana z Kolna", "Ulica Wincentego Janasa", "Jezuicka", "Ulica Kamienna", "Ulica Kanonia", "Ulica Karmelicka", "Ulica Jana Kasprowicza", "Ulica Katedralna", "Ulica Katowicka", "Kijowska", "Ulica Jana Kilinskiego", "Ulica Klasztorna", "Ulica Kolejowa", "Ulica Komuny Paryskiej", "Ulica Stanislawa Konarskiego", "Ulica Mikolaja Kopernika", "Ulica Janusza Korczaka", "Ulica Tadeusza Kosciuszki", "Ulica Krakowska", "Krakowskie Przedmiescie", "Ulica Zygmunta Krasinskiego", "Krolewska", "Ulica Krolowej Jadwigi", "Ulica Krucza", "Ulica Krupnicza", "Lechicka", "Aleja Legionow", "Ulica Legionow", "Ulica Boleslawa Limanowskiego", "Ulica Lipowa", "Ulica Lubelska", "Ulica Lwowska", "Ulica Lakowa", "Ulica Lodzka", "Ulica Jacka Malczewskiego", "Ulica Stanislawa Malachowskiego", "Ulica Mariacka", "Ulica Adama Mickiewicza", "Ulica Mikolowska", "Ulica Miodowa", "Ulica Mlynska", "Ulica Stanislawa Moniuszki", "Ulica Mostowa", "Ulica Gabriela Narutowicza", "Aleja Niepodleglosci", "Ulica Niestachowska", "Ulica Nowa", "Obornicka", "Obozowa", "Ulica Ogrodowa", "Ulica Okopowa", "Ulica Karola Olszewskiego", "Ulica Opolska", "Ulica Oswiecimska";

const plAlphabet = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "N", "O", "P", "R", "S", "T", "U", "W", "Y", "Z", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0"];

const data = {
    us: {
        firstNames: usFirstNames,
        lastNames: usLastNames,
        middleNames: usMiddlenames,
        country: "USA",
        cities: usCities,
        streets: usStreets,
        phoneCode: "+12",
        alphabet: usAlphabet
    },
    by: {
        firstNames: byFirstNames,
        lastNames: byLastNames,
        middleNames: byMiddlNames,
        country: "Беларусь",
        cities: byCities,
        streets: byStreets,
        phoneCode: "+375",
        alphabet: byAlphabet
    },
    pl: {
        firstNames: plFirstNames,
        lastNames: plLastNames,
        middleNames: null,
        country: "Polska",
        cities: plCities,
        streets: plStreets,
        phoneCode: "+48",
        alphabet: plAlphabet
    }
}

exports.data = data;